timezone: Europe/Stockholm
highlighter: pygments
#markdown: rdiscount
markdown: redcarpet
collections:
  front_sections:
    foo: bar
    output: true

# Custom vars
current_version:  1.4.8
repo: https://github.com/bonny/WordPress-Simple-Fields/

